version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credit-app-php
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: credit-app-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network

  db:
    image: mariadb:latest
    container_name: credit-app-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: credit_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
